version: '3.8'

services:
  vsl-detect:
    build:
      context: ..
      dockerfile: dev/Dockerfile
    container_name: vsl-detection-app
    ports:
      - "8080:8080"
    volumes:
      - ../models:/app/models
      - ../config:/app/config
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    
  # Optional: Development service with live reload
  vsl-detect-dev:
    build:
      context: ..
      dockerfile: dev/Dockerfile
    container_name: vsl-detection-dev
    ports:
      - "8081:8080"
    volumes:
      - ..:/app
      - ../models:/app/models
      - ../config:/app/config
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - DEBUG=1
    command: python main.py --debug
    profiles:
      - dev